version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Faza123
      MYSQL_DATABASE: crud_app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Faza123
      DB_NAME: crud_app
      PORT: 5000
      JWT_SECRET: devopsFazaSuperSecretKey
    ports:
      - "5001:5000"
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge